services:
  grafana:
    user: root
    container_name: 'grafana-github-datasource'

    platform: 'linux/amd64'
    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-10.4.2}
        development: ${DEVELOPMENT:-true}
    ports:
      - 3000:3000/tcp
      - 2345:2345/tcp # delve
    security_opt:
      - 'apparmor:unconfined'
      - 'seccomp:unconfined'
    cap_add:
      - SYS_PTRACE
    volumes:
      - ./dist:/var/lib/grafana/plugins/grafana-github-datasource
      - ./provisioning:/etc/grafana/provisioning
      - .:/root/grafana-github-datasource

    environment:
      NODE_ENV: development
      GF_LOG_FILTERS: plugin.grafana-github-datasource:debug
      GF_LOG_LEVEL: debug
      GF_DATAPROXY_LOGGING: 1
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: grafana-github-datasource
